# Generated by Django 5.2.8 on 2026-01-17 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shopper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopper_id', models.CharField(max_length=255, unique=True)),
                ('sticker_balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('store_id', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stickers_earned', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('items_data', models.JSONField()),
                ('shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='stickers.shopper')),
            ],
        ),
    ]
